version: '3'

services:
  all:
    build: ./docker/allinone
    env_file:
      - ./documents/document-variables.env
    volumes:
      - ./documents/doxygen:/tmp/Doxygen/
      - ./documents/doxygen-source:/tmp/Doxygen-source/
      - ./documents:/docs
      - ../TACNET src code/:/tmp/sources
    #command: sh -c "ls -la /tmp/ && doxygen /tmp/Doxygen-source/doxygen-config"

#  sphinxdoc:
#    build: ./docker/sphinxdocs
#    env_file:
#      - ./documents/document-variables.env
#    volumes:
#      - ./documents:/docs
#
#  webserver:
#    image: pierrezemb/gostatic:latest
#    volumes:
#      - ./documents:/srv/http
#    ports:
#      - 8080:8043
#    command: /usr/bin/hastatic
