version: '3'

services:
  doxygen:
    build: ./docker/doxygen
    env_file:
      - ./documents/document-variables.env
    volumes:
      - ./documents/doxygen:/tmp/Doxygen/
      - ./documents/doxygen-source:/tmp/Doxygen-source/
      - ./sources/:/tmp/sources
    command: sh -c "doxygen /tmp/Doxygen-source/doxygen-config"

  sphinxdoc:
    build: ./docker/sphinxdocs
    env_file:
      - ./documents/document-variables.env
    volumes:
      - ./documents:/docs

#  sphinxdoclatex:
#    build: ./docker/sphinxdocslatex
#    volumes:
#      - ./documents:/docs
#    command: make latexpdf
